apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-autoatendimento-queue
  name: app-autoatendimento-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-autoatendimento-queue
  template:
    metadata:
      labels:
        app: app-autoatendimento-queue
    spec:
      containers:
        - image: rafaelbgil/fiap-autoatendimento-app-pedido:1.17
          name: fiap-pos-tech
          command: ["celery"]
          args: ["-A", "autoatendimento", "worker", "-l", "INFO"]
          env:
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: fiap
            - name: CATALOGO_API_URL
              value: "http://catalogo:8000"
            - name: COBRANCA_API_URL
              value: "http://cobranca:8000"
            - name: RABBIT_SERVER
              value: "rabbitmq"

          #Secrets como variavies para acesso ao banco
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-db
                  key: DATABASE_HOST
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-db
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-db
                  key: DATABASE_PASSWORD
            - name: DJANGO_KEY
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-db
                  key: DJANGO_KEY

          #Secrets como variavies para aws
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-aws
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-aws
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-aws
                  key: AWS_DEFAULT_REGION

          #Secrets como variavies cognito
            - name: COGNITO_POOL
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-cognito
                  key: COGNITO_POOL
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-cognito
                  key: COGNITO_CLIENT_ID
            - name: COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fiap-secrets-cognito
                  key: COGNITO_CLIENT_SECRET

            #Para integracao com mercadopago descomentar as variavies abaixo
            #- name: MERCADOPAGO_TOKEN
            #  value: token_vendedor
            #- name: MERCADOPAGO_EMAIL
            #  value: email_comprador
            #- name: WEBHOOK_DOMAIN
            # value: 'https://teste.com.br'
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m

          
